### ISSUE TITLE
Impossible to install if importing Seurat

### ISSUE THREAD

**Issue by Albluca** [dynverse/dynnormaliser#2]
Hi there,

I've been trying to install dynnormaliser as it is a dependency of dyngen. However if try installing the package I get the following error

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  impossible de charger l'objet partagé '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/locfit/libs/locfit.so':
  `nombre maximal de DLLs atteint...

The error is in French, but basically it is complaining that too many DLL has been loaded. It seems to be connected to R being unable to load more than 100 DLLs. After playing around a bit, I found out that the problem is related to the following import statements:

importFrom(Seurat,CreateSeuratObject)
importFrom(Seurat,FindAllMarkers)

If I comment them out, the package compilation is successful. I also tried loading Seurat after loading dyngen, and I get the same error, so basically it seems like the package as a whole is trying to load too much stuff. Is there any specific issue if Seurat is not loaded (beside being unable to manage Seurat object)?

Best wishes,
Luca

**Comment by zouter** [comment]
Hi Luca
This is indeed related to the problem of R loading too many DLLs. As this is quite a common problem (eg. 
 simply loading both Seurat and scran already hits the DLL limit: https://twitter.com/AMA2020/status/979471436460052485 ), I would suggest you add `R_MAX_NUM_DLLs=500`  to your ~/.Renviron file . On a Mac this value should be lower (150 seems to work).

I will have a look later today whether we can limit the number of packages, as Seurat is only used once in the package.

Thanks!
Wouter

**Comment by rcannood** [comment]
It's good that you mention this; I forgot to add this to the installation instructions shown on [https://github.com/dynverse/dynverse](https://github.com/dynverse/dynverse).

**Comment by Albluca** [comment]
Hi Wouter,

thank you for your answer! I wasn't aware that you could increase the number of loadable DLLs in recent R versions. I increased it on my Mac and now I was able to compile including Seurat. I used 150, you can probably make it a bit larger, but not terribly larger as apparently there are some system level limitation on the number of files an executable can open ...

Moreover on my machine the configuration file is called Renviron (without the dot, so it is not a hidden file) and is located in the /Library/Frameworks/R.framework/Versions/3.4/Resources/etc/ subdirectory. Editing ~/.Renviron should have been working as well, but in my case resulted in RStudio not being able to load ...

BW,
Luca

**Comment by rcannood** [comment]
Hi Luca,

I think if the file is called 'Renviron', RStudio will not be able to find
it. However, indeed, on a Mac OS X, setting it to 500 is too much and will
cause R session not to load.

I have now added the R_MAX_NUM_DLLS setting to the dynverse README:
https://github.com/dynverse/dynverse#mac-os-x. Could you make sure that the
~/.Renviron file contains exactly "R_MAX_NUM_DLLS=150" and try again? (and
not "R_MAX_NUM_DLLs=200  inside .Rinviron" as suggested by the tweet).

You can test whether the parameter is set correctly by starting a new R
session and running:
> Sys.getenv("R_MAX_NUM_DLLS")
[1] "250"

Kind regards,
Robrecht

**Comment by Albluca** [comment]
Hi Robrecht,

I added the command to the Renviron file located in /Library/Frameworks/R.framework/Versions/3.4/Resources/etc/ and everything works. And yes I checked with Sys.getenv and the environment variable has been correctly set. (See also here: https://github.com/bvieth/powsimR/issues/1)

This is not RStudio related BTW as the /Library/Frameworks/R.framework/Versions/3.4/Resources/etc/ directory is where R puts its configuration files on a Mac apparently. I believe this is the machine configuration file and you may need to have root privileges in order to modify it. I'll check if I can manage to fix the issue by using ~/.Renviron instead some time later today and I'll let you know :) 

BW,
Luca

**Comment by rcannood** [comment]
Aha! Ok, /Library/Frameworks/R.framework/Versions/3.4/Resources/etc/Renviron
makes sense.

You don't need to try it out with ~/.Renviron as well.

Is dynnormaliser/dyngen working for you, now?

Robrecht

**Comment by Albluca** [comment]
Hi Robrecht,

yes, it's working quite well, thank you. I'm actually generating a couple of sample datasets to use in the ElPiGraph.R paper :)

BW,
Luca

**Comment by zouter** [comment]
Awesome! Good luck with the ElPiGraph.R paper :+1: If you have some difficulties with generating the datasets, we're always willing to help.
